# Конфигурация команд cargo

# Переменные окружения, установленные для всех команд "cargo ...`
[env]

# Уменьшаем масштаб трассировки, чтобы отфильтровать трассировку внешних библиотек.
RUST_LOG="rest_api_server_axum_tutorial=debug"

# -- Переменные окружения
# ВАЖНО:
# Только для команд cargo.
# Для deploy env управление должно осуществляться контейнером
# (например, Kubernetes или Docker).

## -- Secret
# Приведенные ниже ключи и пароли предназначены только для разработчиков localhost (в реальном приложении
# нужно использовать зашифрованные ключи и пароли).
SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"


##--ConfigMap
SERVICE_WEB_FOLDER="web-folder/"